// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassGuard.DAL;

#nullable disable

namespace PassGuard.DAL.Migrations
{
    [DbContext(typeof(PassGuardContext))]
    [Migration("20260408013304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PassGuard.Models.Estate", b =>
                {
                    b.Property<int>("EstateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstateId"));

                    b.Property<string>("EstateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstateId");

                    b.ToTable("Estates");
                });

            modelBuilder.Entity("PassGuard.Models.GateCheckIn", b =>
                {
                    b.Property<int>("GateCheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GateCheckInId"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VisitPassId")
                        .HasColumnType("int");

                    b.HasKey("GateCheckInId");

                    b.HasIndex("VisitPassId");

                    b.ToTable("GateCheckIns");
                });

            modelBuilder.Entity("PassGuard.Models.Home", b =>
                {
                    b.Property<int>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstateId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HomeId");

                    b.HasIndex("EstateId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("PassGuard.Models.VisitPass", b =>
                {
                    b.Property<int>("VisitPassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitPassId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitorPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VisitPassId");

                    b.HasIndex("HomeId");

                    b.ToTable("VisitPasses");
                });

            modelBuilder.Entity("PassGuard.Models.GateCheckIn", b =>
                {
                    b.HasOne("PassGuard.Models.VisitPass", "VisitPass")
                        .WithMany("GateCheckIns")
                        .HasForeignKey("VisitPassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitPass");
                });

            modelBuilder.Entity("PassGuard.Models.Home", b =>
                {
                    b.HasOne("PassGuard.Models.Estate", "Estate")
                        .WithMany("Homes")
                        .HasForeignKey("EstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estate");
                });

            modelBuilder.Entity("PassGuard.Models.VisitPass", b =>
                {
                    b.HasOne("PassGuard.Models.Home", "Home")
                        .WithMany("VisitPasses")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");
                });

            modelBuilder.Entity("PassGuard.Models.Estate", b =>
                {
                    b.Navigation("Homes");
                });

            modelBuilder.Entity("PassGuard.Models.Home", b =>
                {
                    b.Navigation("VisitPasses");
                });

            modelBuilder.Entity("PassGuard.Models.VisitPass", b =>
                {
                    b.Navigation("GateCheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
